-- ==============================================================================
-- Trace Dispatch: Database & Storage Schema
-- Run this SQL in your Supabase Project -> SQL Editor
-- ==============================================================================

-- 1. Create the dispatches table (with 7-day retention & save flag)
CREATE TABLE IF NOT EXISTS public.dispatches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    audio_url TEXT NOT NULL,
    storage_path TEXT,
    duration NUMERIC(6, 2) NOT NULL DEFAULT 0.0,
    transcribed BOOLEAN NOT NULL DEFAULT FALSE,
    transcript TEXT,
    saved BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Migration query if you already created the table without the 'saved' column:
ALTER TABLE public.dispatches ADD COLUMN IF NOT EXISTS saved BOOLEAN NOT NULL DEFAULT FALSE;

-- 2. Create indices for high-performance queries, real-time indexing, and retention purges
CREATE INDEX IF NOT EXISTS idx_dispatches_created_at ON public.dispatches (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_dispatches_transcribed ON public.dispatches (transcribed);
CREATE INDEX IF NOT EXISTS idx_dispatches_saved ON public.dispatches (saved);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.dispatches ENABLE ROW LEVEL SECURITY;

-- 4. Create policies to allow public anon read, insert, and update
-- Note: In production you can restrict updates/inserts using Supabase auth or service role key.
CREATE POLICY "Allow public read access on dispatches"
    ON public.dispatches FOR SELECT
    USING (true);

CREATE POLICY "Allow public insert on dispatches"
    ON public.dispatches FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Allow public update on dispatches"
    ON public.dispatches FOR UPDATE
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow public delete on dispatches"
    ON public.dispatches FOR DELETE
    USING (true);

-- 5. Enable Realtime on the dispatches table
ALTER PUBLICATION supabase_realtime ADD TABLE public.dispatches;

-- ==============================================================================
-- Supabase Storage Bucket Setup Instructions:
-- ==============================================================================
-- In the Supabase Dashboard:
-- 1. Go to "Storage" -> Click "New Bucket"
-- 2. Set Name to: dispatch-clips
-- 3. Toggle "Public bucket" to ON (so audio can be played directly in browser and sent to Groq)
-- 4. Set Allowed MIME types to: audio/mpeg, audio/mp3, audio/* (or leave empty for all)
--
-- Or run the SQL below to create and configure the storage bucket via SQL:
INSERT INTO storage.buckets (id, name, public)
VALUES ('dispatch-clips', 'dispatch-clips', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Policy to allow public reads from the dispatch-clips storage bucket
CREATE POLICY "Public Read Access on dispatch-clips"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'dispatch-clips');

-- Policy to allow uploads to dispatch-clips bucket
CREATE POLICY "Allow Uploads to dispatch-clips"
    ON storage.objects FOR INSERT
    WITH CHECK (bucket_id = 'dispatch-clips');

-- Policy to allow updates/deletions on dispatch-clips
CREATE POLICY "Allow Updates to dispatch-clips"
    ON storage.objects FOR UPDATE
    USING (bucket_id = 'dispatch-clips');

CREATE POLICY "Allow Deletes to dispatch-clips"
    ON storage.objects FOR DELETE
    USING (bucket_id = 'dispatch-clips');
